name: data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://results.texas-election.com/static/data/election/49664/1009/County.json
          downloaded_filename: texas-g-2024-results-county.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://results.texas-election.com/static/data/election/49664/1009/OfficeSummary.json
          downloaded_filename: texas-g-2024-results-summary.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://results.texas-election.com/static/data/election/49664/1009/Home.json
          downloaded_filename: texas-g-2024-results-home.json
